/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Sun Feb 20 21:28:44 2022 */

/* parameterized module instance */
DebugPLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
