/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Fri Feb 25 12:16:34 2022 */

/* parameterized module instance */
DebugPLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
