/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Sat Feb 19 21:22:39 2022 */

/* parameterized module instance */
DIV4PLL __ (.CLKI( ), .CLKOP( ), .LOCK( ));
