//=============================================================================
// Verilog module generated by IPExpress    07/29/2023    16:04:06         
// Filename: counters_inst.v                                          
// Copyright(c) 2006 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

/* WARNING - Changes to this file should be performed by re-running IPexpress
or modifying the .LPC file and regenerating the core.  Other changes may lead
to inconsistent simulation and/or implemenation results */

counters (
    .clk		(clk),
    .reset_n		(reset_n),
    .jtck		(jtck),
    .jrstn		(jrstn),
    .jce2		(jce2),
    .jtdi		(jtdi),
    .er2_tdo		(er2_tdo),
    .jshift		(jshift),
    .jupdate		(jupdate),
    .trigger_din_0	(trigger_din_0),
    .trigger_din_1	(trigger_din_1),
    .trace_din		(trace_din),
    .ip_enable    	(ip_enable)
)

object /* synthesis GSR=DISABLED */
object /* synthesis UGROUP=”counters_core” */
pragma // attribute UGROUP ”counters_core” 
;

